<a href="https://colab.research.google.com/github/GuilhermeGC05/teste-tp-paa3/blob/main/pratica_3_ccf425_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> Introdução à Ciência dos Dados \
> Ciência da Computação – UFV/Florestal


* **Nome:** %s
* **Matrícula:**  %d

# Atividade Prática 03
## Análise Exploratória de Dados

**Objetivo:** Entender comandos para filtro e preparação de dados.
**Pré-requisitos:** Linguagem de programação Python, estatística básica \
**Meta:** Ao final da prática, o aluno será capaz de analisar um conjunto de dados e filtrar e conhecer melhor os dados.

----

In [20]:
### NÃO REMOVA ESSA CÉLULA! ####
!pip --no-cache-dir install --upgrade learntools_dados_ufv

!wget https://raw.githubusercontent.com/NESPEDUFV/CCF425-resources/master/p3/OnlineRetail.xlsx

Requirement already satisfied: learntools_dados_ufv in /usr/local/lib/python3.12/dist-packages (1.0.14.6)
--2026-03-30 13:23:42--  https://raw.githubusercontent.com/NESPEDUFV/CCF425-resources/master/p3/OnlineRetail.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23715344 (23M) [application/octet-stream]
Saving to: ‘OnlineRetail.xlsx.2’

OnlineRetail.xlsx.2 100%[===================>]  22.62M  --.-KB/s    in 0.1s

2026-03-30 13:23:42 (196 MB/s) - ‘OnlineRetail.xlsx.2’ saved [23715344/23715344]

In [26]:
#### Não altere essa célula!!! ####
import pandas as pd


from learntools_dados_ufv.core import binder; binder.bind(globals())
from learntools_dados_ufv.ccf425.pratica_5 import *

WARNING:root:Ignoring repeated attempt to bind to globals

# Roteiro

## Leitura dos dados
Veja os dados do arquivo `OnlineRetail.xlsx`.

Note que o arquivo é um Excel. A biblioteca consegue ler e o interpretar da mesma maneira que um CSV, como estamos acostumados.

Note que a função usada é a `read_excel` e não a `read_csv`.

É normal que demore um pouco, pois os arquivos em excel possuem muito mais recursos e dados armazenados do que um simples csv.

In [ ]:
df = pd.read_excel('./OnlineRetail.xlsx')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

## Explorar os dados

### Verificar quais atributos (colunas) fazem parte dos dados

In [ ]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

### Verificar o tipo de cada atributo

In [ ]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

### Avaliar alguns objetos

In [ ]:
# Veja os 5 primeiros registros
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
# Veja os 10 últimos registros
df.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

### Calcular o número de objetos

In [ ]:
# Número de instâncias/objetos/linhas
len(df)

541909

### Verificar a forma (instâncias, atributos)

In [ ]:
# O primeiro elemento da tupla é a quantidade de instâncias, e o segundo elemento a quatnidade de atributos/colunas
df.shape

(541909, 8)

### Contar objetos de cada valor distinto para um atributo

In [ ]:
# Conta quantas vezes cada item aparece em uma coluna
df['Description'].value_counts()

Description
WHITE HANGING HEART T-LIGHT HOLDER     2369
REGENCY CAKESTAND 3 TIER               2200
JUMBO BAG RED RETROSPOT                2159
PARTY BUNTING                          1727
LUNCH BAG RED RETROSPOT                1638
                                       ...
Missing                                   1
historic computer difference?....se       1
DUSTY PINK CHRISTMAS TREE 30CM            1
WRAP BLUE RUSSIAN FOLKART                 1
PINK BERTIE MOBILE PHONE CHARM            1
Name: count, Length: 4223, dtype: int64

### Mostrar a taxa de objetos de cada valor distinto para um atributo

In [ ]:
# Faz a normalização com o percentual de cada valor
df['Description'].value_counts(normalize=True)

Description
WHITE HANGING HEART T-LIGHT HOLDER     0.004383
REGENCY CAKESTAND 3 TIER               0.004071
JUMBO BAG RED RETROSPOT                0.003995
PARTY BUNTING                          0.003195
LUNCH BAG RED RETROSPOT                0.003031
                                         ...
Missing                                0.000002
historic computer difference?....se    0.000002
DUSTY PINK CHRISTMAS TREE 30CM         0.000002
WRAP BLUE RUSSIAN FOLKART              0.000002
PINK BERTIE MOBILE PHONE CHARM         0.000002
Name: proportion, Length: 4223, dtype: float64

### Verificar quantos valores ausentes existes em um atributo

In [ ]:
# A função retorna se os valores são nulos ou não. Ou seja, False == existe um valor para a linha | True == o valor é nulo.
pd.isnull(df['Description']).value_counts()

Description
False    540455
True       1454
Name: count, dtype: int64

### Apagar os objetos com valores nulos/ausentes de alguma coluna

In [ ]:
df = df.dropna(axis=0, subset=['Description'])
pd.isnull(df['Description']).value_counts()

Description
False    540455
Name: count, dtype: int64

### Filtrar por índice da linha

In [ ]:
df.loc[2]

'United Kingdom'

### Filtrar por faixa de índices

In [ ]:
df[2:8]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom

### Filtrar pelo nome de uma coluna

In [ ]:
# Recupera somente a descrição dos 5 primeiros registros
df[['Description']].head(5)

                           Description
0   WHITE HANGING HEART T-LIGHT HOLDER
1                  WHITE METAL LANTERN
2       CREAM CUPID HEARTS COAT HANGER
3  KNITTED UNION FLAG HOT WATER BOTTLE
4       RED WOOLLY HOTTIE WHITE HEART.

### Filtrar por mais de uma coluna

In [ ]:
df[['Description', 'InvoiceNo']].head(5)

                           Description InvoiceNo
0   WHITE HANGING HEART T-LIGHT HOLDER    536365
1                  WHITE METAL LANTERN    536365
2       CREAM CUPID HEARTS COAT HANGER    536365
3  KNITTED UNION FLAG HOT WATER BOTTLE    536365
4       RED WOOLLY HOTTIE WHITE HEART.    536365

### Filtrar por índice de linha em uma coluna específica

In [ ]:
# Qual o valor da coluna "Description" na 5ª linha?
df.loc[536365, 'InvoiceNo']

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
StockCode,,,,,,,
23405,565478,HOME SWEET HOME 2 DRAWER CABINET,1,2011-09-05 11:18:00,4.95,15005.0,United Kingdom
23405,565674,HOME SWEET HOME 2 DRAWER CABINET,4,2011-09-06 09:49:00,4.95,15271.0,United Kingdom
23405,566026,HOME SWEET HOME 2 DRAWER CABINET,4,2011-09-08 12:56:00,4.95,15618.0,United Kingdom
23405,566198,HOME SWEET HOME 2 DRAWER CABINET,4,2011-09-09 13:58:00,4.95,18109.0,United Kingdom
23405,566446,HOME SWEET HOME 2 DRAWER CABINET,1,2011-09-12 15:40:00,10.79,NaN,United Kingdom
...,...,...,...,...,...,...,...
23405,580322,HOME SWEET HOME 2 DRAWER CABINET,8,2011-12-02 15:48:00,4.95,17567.0,United Kingdom
23405,580730,HOME SWEET HOME 2 DRAWER CABINET,1,2011-12-05 17:28:00,10.79,NaN,United Kingdom
23405,581057,HOME SWEET HOME 2 DRAWER CABINET,4,2011-12-07 11:03:00,4.95,16817.0,United Kingdom
23405,581219,HOME SWEET HOME 2 DRAWER CABINET,1,2011-12-08 09:28:00,10.79,NaN,United Kingdom
23405,581492,HOME SWEET HOME 2 DRAWER CABINET,3,2011-12-09 10:03:00,10.79,NaN,United Kingdom

### Filtrar pelos valores de uma coluna

In [ ]:
df[df['Country'] == 'Brazil'].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
157299,550201,22423,REGENCY CAKESTAND 3 TIER,16,2011-04-15 10:25:00,10.95,12769.0,Brazil
157300,550201,22699,ROSES REGENCY TEACUP AND SAUCER,24,2011-04-15 10:25:00,2.55,12769.0,Brazil
157301,550201,22697,GREEN REGENCY TEACUP AND SAUCER,24,2011-04-15 10:25:00,2.55,12769.0,Brazil
157302,550201,22698,PINK REGENCY TEACUP AND SAUCER,24,2011-04-15 10:25:00,2.55,12769.0,Brazil
157303,550201,22366,DOORMAT AIRMAIL,10,2011-04-15 10:25:00,6.75,12769.0,Brazil

### Filtrar utilizando expressões lógicas

In [ ]:
df[(df['Country'] == 'Brazil') & (df['Quantity'] > 15)].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
157299,550201,22423,REGENCY CAKESTAND 3 TIER,16,2011-04-15 10:25:00,10.95,12769.0,Brazil
157300,550201,22699,ROSES REGENCY TEACUP AND SAUCER,24,2011-04-15 10:25:00,2.55,12769.0,Brazil
157301,550201,22697,GREEN REGENCY TEACUP AND SAUCER,24,2011-04-15 10:25:00,2.55,12769.0,Brazil
157302,550201,22698,PINK REGENCY TEACUP AND SAUCER,24,2011-04-15 10:25:00,2.55,12769.0,Brazil
157304,550201,21430,SET/3 RED GINGHAM ROSE STORAGE BOX,24,2011-04-15 10:25:00,3.39,12769.0,Brazil

In [ ]:
df[((df['Country'] == 'Brazil') & (df['Description'] == 'PINK REGENCY TEACUP AND SAUCER')) | ((df['Country'] == 'Japan') & (df['Quantity'] > 1000))].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
19871,537899,22328,ROUND SNACK BOXES SET OF 4 FRUITS,1488,2010-12-09 10:44:00,2.55,12755.0,Japan
157302,550201,22698,PINK REGENCY TEACUP AND SAUCER,24,2011-04-15 10:25:00,2.55,12769.0,Brazil
511421,579498,23084,RABBIT NIGHT LIGHT,2040,2011-11-29 15:52:00,1.79,12798.0,Japan

### Criar um novo atributo derivado em outros

In [ ]:
df['TotalPrice'] = (df['Quantity'].copy() * df['UnitPrice'].copy())
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

### Apagar uma instância por índice da linha

In [ ]:
# Apagando a terceira linha
df2 = df.drop(2)
df2.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,15.30

### Apagar uma coluna

In [ ]:
df2 = df2.drop('TotalPrice', axis=1)
df2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

### Criar um índice por um atributo

In [ ]:
# Índices ajudam a filtrar
df = df.set_index('InvoiceNo')

In [ ]:
df.loc[536365]

,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
InvoiceNo,,,,,,,,
536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,15.30
536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,25.50

### Cancelar os índices que foram criados

In [ ]:
df.reset_index(inplace = True)
df.index

RangeIndex(start=0, stop=541909, step=1)

### Filtrar e calcular valores estatísticos de um atributo com valores numéricos

In [ ]:
df[df['Country'] == 'Brazil']['UnitPrice'].mean()

4.456250000000001

In [ ]:
df[df['Country'] == 'France']['UnitPrice'].mean()

5.028864087881266

In [ ]:
df[df['Country'] == 'Brazil']['Quantity'].median()

10.0

In [ ]:
df[df['Country'] == 'Japan']['Quantity'].median()

36.0

### Agrupar por um atributo e calcular estatísticas desse grupo

In [ ]:
df_gb_description = df.groupby('Description')

df_gb_description['UnitPrice'].count()

Description
20713                               1
 4 PURPLE FLOCK DINNER CANDLES     41
 50'S CHRISTMAS GIFT BAG LARGE    130
 DOLLY GIRL BEAKER                181
 I LOVE LONDON MINI BACKPACK       88
                                 ...
wrongly marked carton 22804         1
wrongly marked. 23343 in box        1
wrongly sold (22719) barcode        1
wrongly sold as sets                1
wrongly sold sets                   1
Name: UnitPrice, Length: 4223, dtype: int64

In [ ]:
df_gb_description['Country'].count().head()

Description
20713                               1
 4 PURPLE FLOCK DINNER CANDLES     41
 50'S CHRISTMAS GIFT BAG LARGE    130
 DOLLY GIRL BEAKER                181
 I LOVE LONDON MINI BACKPACK       88
Name: Country, dtype: int64

In [ ]:
df_gb_description['UnitPrice'].sum().head()

Description
20713                               0.00
 4 PURPLE FLOCK DINNER CANDLES    100.67
 50'S CHRISTMAS GIFT BAG LARGE    185.28
 DOLLY GIRL BEAKER                271.38
 I LOVE LONDON MINI BACKPACK      405.80
Name: UnitPrice, dtype: float64

In [ ]:
df.columns

Index(['index', 'InvoiceNo', 'StockCode', 'Description', 'Quantity',
       'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'TotalPrice'],
      dtype='object')

In [ ]:
df.groupby(["CustomerID"])["StockCode"].count()

CustomerID
12346.0      2
12347.0    182
12348.0     31
12349.0     73
12350.0     17
          ...
18280.0     10
18281.0      7
18282.0     13
18283.0    756
18287.0     70
Name: StockCode, Length: 4372, dtype: int64

# Exercícios

Execute e não remova a célula abaixo antes de iniciar os exercícios. Faça todas as atividades manipulando a variável `df`.

In [24]:
# Atribui o dataframe com o estado "original" em uma variável isolada
original_df = pd.read_excel('./OnlineRetail.xlsx')[0]
df = original_df
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

## 1. Recupere a quantidade de instâncias com Notas Fiscais ausentes/nulas
Armazene-a na variável `missing_invoice_no`.

Chame a função `q1.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q1.hint()`

In [45]:
missing_invoice_no = int(df['InvoiceNo'].isnull().sum())

q1.check()

CORRETO:

## 2. Recupere a quantidade de instâncias com Preço Unitário menor que zero.
Armazene-a na variável `invalid_unit_price`.

Chame a função `q2.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q2.hint()`

In [52]:
# q2.hint()

invalid_unit_price = int((df['UnitPrice'] < 0).sum())

q2.check()

CORRETO:

## 3. Remova todos as instâncias que possui o Preço Unitário inválido.
Reatribua o dataframe filtrado na variável `df`.

Chame a função `q3.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q3.hint()`

In [48]:
 #q3.hint()

df = df.drop(df[df['UnitPrice'] < 0].index)

q3.check()

Dica 1: Pesquise sobre a função `df.drop` do Pandas.
(Para outra dica, chame `.hint(2)`)

CORRETO:

## 4. Recupere o ID do Cliente que comprou mais itens.
Armazene-o na variável `top_customer_id`.

Chame a função `q4.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q4.hint()`

In [57]:
int(df.groupby(["CustomerID"])["Quantity"].count().idxmax())

17841

In [56]:
# q4.hint()

top_customer_id = int(df.groupby(["CustomerID"])["Quantity"].count().idxmax())
print('top_customer_id', top_customer_id)
q4.check()

top_customer_id 17841

CORRETO:

## 5. Recupere a descrição do produto mais caro vendido.
Armazene-o na variável `most_expensive_product`.

Chame a função `q5.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q5.hint()`

In [59]:
df.loc[df['UnitPrice'].idxmax()]['Description']

'Manual'

In [60]:
# q5.hint()

most_expensive_product = df.loc[df['UnitPrice'].idxmax()]['Description']

q5.check()

CORRETO:

## 6. Recupere a % relativa das instâncias atribuídas ao país `Germany` excluindo o país `United Kingdom` da base.
Armazene-a na variável `germany_orders_percentage`.

Chame a função `q6.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q6.hint()`

In [103]:
df.groupby(["Country"])["Quantity"].count().sum()
int((df['Country'] == 'United Kingdom').sum())

np.int64(541907)

In [106]:
#q6.hint()
filtro = int((df['Country'] != 'United Kingdom').sum())
germany = int((df['Country']=='Germany').sum())
germany_orders_percentage = (germany / filtro) * 100

q6.check()

CORRETO:

## 7. Recupere a(s) instância(s) da compra que possui mais itens.
Armazene-a na variável `most_items_order`.

Chame a função `q7.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q7.hint()`

In [140]:
df.groupby(["InvoiceNo"])[""].count()

InvoiceNo
536365      7
536366      2
536367     12
536368      4
536369      1
           ..
C581484     1
C581490     2
C581499     1
C581568     1
C581569     2
Name: Quantity, Length: 25898, dtype: int64

In [123]:
# q7.hint()

most_items_order = df.loc[[df["Quantity"].idxmax()]]

q7.check()

CORRETO:

## 8. Recupere o identificador da compra mais cara.
Armazene-a na variável `most_expensive_order`.

Chame a função `q8.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q8.hint()`

In [142]:
df.groupby(["Quantity"])["UnitPrice"].count()

Quantity
-80995    1
-74215    1
-9600     2
-9360     1
-9058     1
         ..
 4800     1
 5568     1
 12540    1
 74215    1
 80995    1
Name: UnitPrice, Length: 722, dtype: int64

In [135]:
# q8.hint()

most_expensive_order = int(df.groupby(["CustomerID"])["UnitPrice"].sum().idxmax())

q8.check()

INCORRETO: Valor incorreto para most_expensive_order: `14096`

## 9. Responda as questões abertas a seguir:

### 9.a) Qual o objetivo das estatísticas descritivas?

RESPOSTA:

### 9.b) Liste 3 perguntas que poderiam ser respondidas utilizando estatística descritiva com o conjunto de dados trabalhados nessa prática.

RESPOSTA:

### 9.c) Tente responder essas 3 perguntas acima com evidências usando as funcionalidades aprendidas.

RESPOSTA:

In [ ]:
# Código da 9.c

### 9.d) Você acha que estatística descritiva é útil para fazer inferência ou predições? Justifique.

RESPOSTA: